-- Migration 010: Add insight_notifications table for weekly intelligence
--
-- Stores actionable insights generated by the weekly intelligence analyzer.
-- Per-user, dismissable, with categories for filtering.

CREATE TABLE IF NOT EXISTS insight_notifications (
  id              uuid          PRIMARY KEY DEFAULT gen_random_uuid(),
  clerk_user_id   text          NOT NULL,
  title           text          NOT NULL,
  message         text          NOT NULL,
  category        text          NOT NULL DEFAULT 'general',
    -- Categories: source_analysis, role_fit, ghosting_pattern, timing,
    -- score_correlation, pipeline_health, weekly_summary
  priority        text          NOT NULL DEFAULT 'normal',
    -- Priority: low, normal, high
  data            jsonb         NULL,
    -- Structured data backing the insight (charts, numbers, etc.)
  is_dismissed    boolean       NOT NULL DEFAULT false,
  dismissed_at    timestamptz   NULL,
  created_at      timestamptz   NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_insight_notifications_user
  ON insight_notifications (clerk_user_id, is_dismissed, created_at DESC);

-- Deduplication handled in application code (check title within 7 days before insert)
